version: "3.1"

services:
    web:
        image: nginx
        volumes:
            - ./src/html:/usr/share/nginx/html
            - ./dist:/usr/share/nginx/html/assets
        ports:
            - 8080:80
